In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from synthetic_task.plot_results import load_results_QP, load_results_CP, plot_total_loss_vs_method_by_ydim, plot_total_time_vs_method_by_ydim, plot_total_time_vs_ydim_for_methods, plot_time_scaling_vs_ydim, load_results_across_batches, plot_time_scaling_vs_batch

In [2]:
sns.set_theme(style="whitegrid", context="talk")
palette = sns.color_palette()

In [4]:
# PLOT BATCH ABLATION
ROOT = ".."

METHODS = [
    "ffocp_eq",
]
METHODS_LEGEND = {
    "ffocp_eq": "FFOCP",
}

method_order = [METHODS_LEGEND[m] for m in METHODS]

df_all = load_results_across_batches(
    root_dir=ROOT,
    batch_sizes=None,
    loader_fn=load_results_CP,
    methods=METHODS,
    methods_legend=METHODS_LEGEND,
)

method:  ffocp_eq
method:  ffocp_eq
method:  ffocp_eq
method:  ffocp_eq
method:  ffocp_eq
method:  ffocp_eq

In [5]:
df_all

,epoch,train_ts_loss,test_ts_loss,train_df_loss,test_df_loss,forward_time,backward_time,method,seed,n,lr,ydim,batch_size
0,0,57.452311,0.0,-0.464479,0.0,434.527348,428.260238,FFOCP,1,NaN,0.001,800,1
1,0,50.233187,0.0,-0.465843,0.0,468.582487,462.893587,FFOCP,2,NaN,0.001,800,1
2,0,58.097721,0.0,-0.464782,0.0,480.707573,475.793314,FFOCP,3,NaN,0.001,800,1
3,0,56.541165,0.0,-0.470788,0.0,478.779373,474.103904,FFOCP,4,NaN,0.001,800,1
4,0,54.126785,0.0,-0.463682,0.0,482.228468,477.997777,FFOCP,5,NaN,0.001,800,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,0,1.596674,0.0,-0.441706,0.0,89.305095,97.298301,FFOCP,5,NaN,0.001,800,16
70,0,0.988028,0.0,-0.389009,0.0,85.063648,95.986092,FFOCP,1,NaN,0.001,800,32
71,0,0.982131,0.0,-0.388680,0.0,82.734893,94.441057,FFOCP,2,NaN,0.001,800,32
72,0,0.987993,0.0,-0.390248,0.0,83.124762,93.911058,FFOCP,3,NaN,0.001,800,32
73,0,0.974203,0.0,-0.387242,0.0,90.870878,102.601617,FFOCP,5,NaN,0.001,800,32

In [8]:
df_all["method"] = pd.Categorical(df_all["method"], categories=method_order, ordered=True)

plot_time_scaling_vs_batch(
    df_all,
    plot_path=ROOT,
    methods_order=method_order,
)

'../syn_batch_scaling_3panels.pdf'

In [9]:
# PLOT GENERAL TASK -- SOC

batch_size = 8
SOC_DIR = f"../synthetic_results_general_{batch_size}"
METHODS = [
    "cvxpylayer",
    "lpgd",
    "bpqp",
    "ffocp_eq",
]
METHODS_LEGEND = {
    "cvxpylayer": "CvxpyLayer",
    "lpgd": "LPGD",
    "bpqp": "BPQP",
    "ffocp_eq": "FFOCP",
}

METHODS_STEPS = [method+"_steps" for method in METHODS]

method_order = [METHODS_LEGEND[m] for m in METHODS]

markers = ["o", "s", "D", "^", "v", "x"]
markers_dict = {method: markers[i] for i, method in enumerate(method_order)}

LINEWIDTH = 1.5

In [10]:
df = load_results_CP(base_dir=SOC_DIR, methods=METHODS, methods_legend=METHODS_LEGEND)
df = df.rename(columns=lambda c: c.strip() if isinstance(c, str) else c)
df["method"] = pd.Categorical(df["method"], categories=method_order, ordered=True)

method:  cvxpylayer
method:  lpgd
method:  bpqp
method:  ffocp_eq

In [11]:
plot_total_time_vs_method_by_ydim(df, SOC_DIR, ('forward_time','backward_time'), tag="syn")

In [12]:
plot_time_scaling_vs_ydim(df, plot_path=SOC_DIR, methods_order=method_order)

In [13]:
# plot all ydim
# selected_methods = ["FFOCP", "BPQP"]
# plot_total_time_vs_ydim_for_methods(
#     df,
#     methods_subset=selected_methods,
#     time_names=('forward_time', 'backward_time'),
#     plot_path=SOC_DIR,
#     plot_name_tag="syn_steps_solve_ffocp_bpqp"
# )

In [14]:
df = load_results_CP(base_dir=SOC_DIR, methods=METHODS_STEPS, methods_legend=METHODS_LEGEND)
df = df.rename(columns=lambda c: c.strip() if isinstance(c, str) else c)
df["method"] = pd.Categorical(df["method"], categories=method_order, ordered=True)

method:  cvxpylayer
method:  lpgd
method:  bpqp
method:  ffocp_eq

In [15]:
df[df["method"] == "FFOCP"].ydim.unique()

array([1000,  200,  300,  400,  500,  600,  700,  800,  900])

In [16]:
plot_total_loss_vs_method_by_ydim(df, SOC_DIR)

In [21]:
# PLOT SYNTHETIC TASK -- QP

batch_size = 8
QP_DIR = f"../synthetic_results_{batch_size}"
METHODS = [
    "cvxpylayer",
    "lpgd",
    "bpqp",
    "ffocp_eq",
    "dqp",
    "qpth",
    "ffoqp_eq_schur",    
]
METHODS_LEGEND = {
    "cvxpylayer": "CvxpyLayer",
    "lpgd": "LPGD",
    "bpqp": "BPQP",
    "ffocp_eq": "FFOCP",
    "dqp": "dQP",
    "qpth": "qpth",
    "ffoqp_eq_schur": "FFOQP",
}

METHODS_STEPS = [method+"_steps" for method in METHODS]

method_order = [METHODS_LEGEND[m] for m in METHODS]

markers = ["o", "s", "D", "^", "v", "x", "P", "s"]
markers_dict = {method: markers[i] for i, method in enumerate(method_order)}

LINEWIDTH = 1.5

In [22]:
df = load_results_QP(base_dir=QP_DIR, methods=METHODS, methods_legend=METHODS_LEGEND)
df = df.rename(columns=lambda c: c.strip() if isinstance(c, str) else c)
df["method"] = pd.Categorical(df["method"], categories=method_order, ordered=True)

method:  cvxpylayer
method:  lpgd
method:  bpqp
method:  ffocp_eq
method:  dqp
method:  qpth
method:  ffoqp_eq_schur

In [23]:
df[df["method"] == "FFOQP"]

,epoch,train_ts_loss,test_ts_loss,train_df_loss,test_df_loss,forward_time,backward_time,method,seed,n,lr,ydim,backwardTol
436,0,2.002229,0.0,-0.468039,0.0,99.561114,35.265574,FFOQP,1,NaN,0.001,1000,NaN
437,0,2.004048,0.0,-0.468603,0.0,93.989844,27.312217,FFOQP,10,NaN,0.001,1000,NaN
438,0,1.981446,0.0,-0.468794,0.0,101.130303,36.416768,FFOQP,2,NaN,0.001,1000,NaN
439,0,2.014030,0.0,-0.468329,0.0,100.519457,34.933484,FFOQP,3,NaN,0.001,1000,NaN
440,0,1.994176,0.0,-0.468258,0.0,98.747680,35.228853,FFOQP,4,NaN,0.001,1000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,1.988679,0.0,-0.469108,0.0,80.720694,29.228782,FFOQP,5,NaN,0.001,900,NaN
522,0,1.990780,0.0,-0.469006,0.0,78.616584,20.049297,FFOQP,6,NaN,0.001,900,NaN
523,0,1.992276,0.0,-0.468968,0.0,89.442196,22.292826,FFOQP,7,NaN,0.001,900,NaN
524,0,1.993443,0.0,-0.469414,0.0,100.181939,27.915672,FFOQP,8,NaN,0.001,900,NaN
525,0,1.995657,0.0,-0.468818,0.0,84.645610,28.476709,FFOQP,9,NaN,0.001,900,NaN

In [24]:
plot_total_time_vs_method_by_ydim(df, QP_DIR, ('forward_time','backward_time'), tag="syn")

filtered_method_order: ['BPQP', 'FFOCP']
available method:  {'FFOCP', 'BPQP'}
groups: ['BPQP', 'FFOCP']
methods: ['BPQP', 'FFOCP']

filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'LPGD', 'FFOCP', 'FFOQP', 'BPQP', 'CvxpyLayer'}
groups: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['CvxpyLayer', 'qpth', 'LPGD', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
filtered_method_order: ['qpth', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
available method:  {'dQP', 'qpth', 'FFOCP', 'FFOQP', 'BPQP'}
groups: ['qpth', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']
methods: ['qpth', 'BPQP', 'dQP', 'FFOCP', 'FFOQP']

In [27]:
plot_time_scaling_vs_ydim(df, plot_path=QP_DIR, methods_order=method_order)

In [9]:
# plot all ydim
selected_methods = ["FFOQP", "BPQP"]
plot_total_time_vs_ydim_for_methods(
    df,
    methods_subset=selected_methods,
    time_names=('forward_time', 'backward_time'),
    plot_path=QP_DIR,
    plot_name_tag="syn_steps_solve_ffocp_bpqp"
)

In [12]:
df = load_results_QP(base_dir=QP_DIR, methods=METHODS_STEPS, methods_legend=METHODS_LEGEND)
df = df.rename(columns=lambda c: c.strip() if isinstance(c, str) else c)
df["method"] = pd.Categorical(df["method"], categories=method_order, ordered=True)

method:  cvxpylayer
method:  lpgd
method:  bpqp
method:  ffocp_eq
method:  dqp
method:  qpth
method:  ffoqp_eq_schur

In [ ]:
plot_total_loss_vs_method_by_ydim(df, QP_DIR)